# data.py
first_folder = os.listdir("Assets/ShapeNet")
    second_folder = os.listdir(os.path.join("Assets/ShapeNet", first_folder[0]))
    file = os.path.join("Assets/ShapeNet/", first_folder[0], second_folder[0], "models", "model_normalized.obj")
    mesh = trimesh.load(file, force="mesh")
    print(mesh.bounds)
    width, height, depth = map(abs, map(lambda x, y : x - y, mesh.bounds[1], mesh.bounds[0]))
    print(width, height, depth)
    size = max(width, height, depth)
    print(size)
    voxel_grid = trimesh.voxel.creation.voxelize(mesh, pitch=size/128)
    print(voxel_grid)